Homework 3 completed
tanyaBrave/TatianaKhrabrova_LevelUp pull request #7
Opened 2021-11-28 11:49 UTC by tanyaBrave

2021-12-01 16:24 UTC, khda91 requested changes
Поправь, пожалуйста, комментарии к работе)

2021-12-01 16:24 UTC, khda91 commented on src/test/java/selenium/exercise1/Exercise1.java
> +public class Exercise1 extends AbstractBaseSeleniumTest {
А зачем было сделано разделение одно теста на несколько?

2021-12-01 16:24 UTC, khda91 commented on src/test/java/selenium/exercise2/Exercise2.java
> +public class Exercise2 extends AbstractBaseSeleniumTest {
В целом вопрос тот же самый, почему тест разбит на несколько тестов?)

2021-12-01 16:24 UTC, khda91 commented on src/test/java/testng/calculator/functional/AbstractBaseCalculatorTest.java
> +public class AbstractBaseCalculatorTest {
А вот файлов из hw2 быть в ПРе не должно) Сделай плиз rebase на `master`/`main` ветку

2021-12-01 16:52 UTC, tanyaBrave commented on src/test/java/selenium/exercise2/Exercise2.java
> +public class Exercise2 extends AbstractBaseSeleniumTest {
потому что это разные пункты в дз)
я предположила один пункт = одна проверка

2021-12-01 16:52 UTC, tanyaBrave commented on src/test/java/selenium/exercise1/Exercise1.java
> +public class Exercise1 extends AbstractBaseSeleniumTest {
потому что это разные пункты в дз)
я предположила один пункт = одна проверка

2021-12-01 16:52 UTC, tanyaBrave commented on src/test/java/testng/calculator/functional/AbstractBaseCalculatorTest.java
> +public class AbstractBaseCalculatorTest {
их изначально и не планировалось, но почему-то гит ругался на коммит без этих изменений

2021-12-01 16:57 UTC, tanyaBrave commented on src/test/java/testng/calculator/functional/AbstractBaseCalculatorTest.java
> +public class AbstractBaseCalculatorTest {
или я папки переименовывала и он из-за этого просил их тоже пушнуть
в общем была какая-то муть и я пошла простым путем

2021-12-14 16:50 UTC, khda91 requested changes
1

2021-12-14 16:51 UTC, khda91 approved these changes
Домашняя работа принята

2021-12-18 12:23 UTC, merged